// Firestore data types

export interface Student {
  id: string
  name: string
  personalId: string
  password: string
  grade: string
  phone: string
  parentPhone: string
  totalProblems: number
  correctAnswers: number
  averageScore: number
  totalLearningTime: number // in seconds
  lastActivity: string
  academyId?: string // Academy association for directors
  directorId?: string // Assigned director/instructor
  createdAt: Date
  updatedAt: Date
}

export interface Textbook {
  id: string
  title: string
  level: string
  page: number
  totalProblems: number
  problems: Problem[]
  // 새 필드들
  majorCategory?: string // 큰_범주_단계
  minorCategory?: string // 작은_범주_단계
  category?: string // 유형
  majorUnit?: string // 대단원명
  subUnits?: SubUnit[] // 소단원 목록
  recommendedGrade?: string // 권장학년
  isActive?: boolean // 활성여부
  createdAt: Date
  updatedAt: Date
}

export interface SubUnit {
  id: string
  name: string // 소단원명
  page: number // 페이지수
  problems: Problem[]
}

export interface Problem {
  number: number
  question: string
  options: string[]
  correctAnswer: string
  // 새 필드들
  type?: "multiple" | "short" | "essay" // 문제유형 (객관식/주관식/서술형)
  passageId?: string // 지문ID
  keywords?: string[] // 서술형 채점 키워드
  domain?: string | null // 영역 (사실적/추론적 이해 등)
  isActive?: boolean // 활성여부
}

export interface CSVProblemRow {
  majorCategory: string // 큰_범주_단계
  minorCategory: string // 작은_범주_단계
  category: string // 유형
  textbookName: string // 문제집_이름
  majorUnit: string // 대단원명
  subUnit: string // 소단원명
  page: number // 페이지수
  passageId: string // 지문ID
  problemNumber: number // 문제번호
  problemType: string // 문제유형
  answer: string // 정답
  recommendedGrade: string // 권장학년
  domain: string // 영역 (사고유형)
  isActive: boolean // 활성여부
}

export interface LearningSession {
  id: string
  studentId: string
  textbookId: string
  textbookName: string
  page: number
  startTime: Date
  endTime?: Date
  readingTime: number // in seconds
  solvingTime: number // in seconds
  totalQuestions: number
  correctCount: number
  results: Record<number, ProblemResult>
  createdAt: Date
}

export interface ProblemResult {
  correct: boolean
  userAnswer: string
  correctAnswer: string
}

export interface Report {
  id: string
  studentId: string
  studentName: string
  academyId?: string
  date: string // "YYYY-MM" or "YYYY-MM-DD"
  type: "monthly" | "completion"
  targetWorkbookId?: string // Only for completion reports
  status: "draft" | "sent"

  // Statistical Data Snapshot
  content: {
    totalProblems: number
    correctAnswers: number
    averageScore: number
    learningTime: number // seconds
    attendanceDays?: number // Only for monthly

    // Domain Analysis (Radar Chart)
    domainScores?: {
      [domain: string]: {
        correct: number
        total: number
        score: number // percentage
      }
    }

    // Comparative Analysis
    comparativeStats?: {
      studentScore: number
      academyAverage: number
      globalAverage: number
    }

    // Completed Units (for Completion Report)
    unitScores?: {
      [unitName: string]: number
    }

    // New Rich Data
    weeklyTrend?: { label: string, count: number }[]
    textbookStats?: {
      [textbookName: string]: {
        total: number
        correct: number
        score: number
      }
    }
  }

  teacherComment?: string // Created by Director (or AI drafted)
  aiCommentDraft?: string // Generated by AI, hidden from student

  createdAt: Date
  sentAt?: Date
}

export interface Admin {
  id: string
  personalId: string
  password: string
  name: string
  createdAt: Date
}

export interface User {
  id: string // Firebase UID
  email: string
  displayName: string
  photoURL?: string
  role: "대표자" | "원장" | "강사" | "학생" | null
  status: "pending" | "approved" | "rejected"
  academyId?: string // Academy association for directors and instructors
  createdAt: Date
  updatedAt: Date
  approvedBy?: string // User ID who approved
  approvedAt?: Date
}

export interface Academy {
  id: string
  name: string
  address: string
  phone: string
  email: string
  directorId: string // User ID of the academy director (원장)
  createdAt: Date
  updatedAt: Date
}

export interface BlogPost {
  doc_id: string
  title: string
  content: string
  thumbnailUrl: string
  keywords: string[]
  createdAt: Date
  author: string
  isPublished: boolean
}
